// @ts-nocheck
import { sqliteTable, AnySQLiteColumn, foreignKey, check, text, integer, index, uniqueIndex } from "drizzle-orm/sqlite-core"
import { sql } from "drizzle-orm"

export const articleVocabDefinitions = sqliteTable("article_vocab_definitions", {
	id: text().primaryKey().notNull(),
	vocabId: text("vocab_id").notNull().references(() => articleVocabulary.id, { onDelete: "cascade" }),
	partOfSpeech: text("part_of_speech").notNull(),
	definition: text().notNull(),
	createdAt: text("created_at").default("sql`(CURRENT_TIMESTAMP)`").notNull(),
},
	(table) => [
		check("chk_tasks_type_enum", sql`"tasks"."type" IN ('article_generation'`),
		check("chk_tasks_trigger_source_enum", sql`"tasks"."trigger_source" IN ('manual', 'cron'`),
		check("chk_tasks_status_enum", sql`"tasks"."status" IN ('queued', 'running', 'succeeded', 'failed', 'canceled'`),
		check("chk_tasks_result_json_valid", sql`"tasks"."result_json" IS NULL OR json_valid("tasks"."result_json"`),
		check("chk_tasks_error_context_json_valid", sql`"tasks"."error_context_json" IS NULL OR json_valid("tasks"."error_context_json"`),
		check("chk_tasks_published_only_for_article_generation", sql`"tasks"."type" = 'article_generation' OR "tasks"."published_at" IS NULL`),
		check("chk_words_origin_enum", sql`"words"."origin" IN ('shanbay', 'article', 'manual'`),
		check("chk_awi_role_enum", sql`"article_word_index"."role" IN ('keyword', 'entity'`),
		check("chk_articles_status_enum", sql`"articles"."status" IN ('draft', 'published'`),
		check("chk_highlights_start_meta_json_valid", sql`json_valid("highlights"."start_meta_json"`),
		check("chk_highlights_end_meta_json_valid", sql`json_valid("highlights"."end_meta_json"`),
		check("chk_highlights_style_json_valid", sql`"highlights"."style_json" IS NULL OR json_valid("highlights"."style_json"`),
		check("chk_daily_word_ref_type_enum", sql`"daily_word_references"."type" IN ('new', 'review'`),
		check("chk_generation_profiles_concurrency_gt0", sql`"generation_profiles"."concurrency" > 0`),
		check("chk_generation_profiles_timeout_ms_gt0", sql`"generation_profiles"."timeout_ms" > 0`),
	]);

export const articleVocabulary = sqliteTable("article_vocabulary", {
	id: text().primaryKey().notNull(),
	articleId: text("article_id").notNull().references(() => articles.id, { onDelete: "cascade" }),
	word: text().notNull(),
	phonetic: text(),
	createdAt: text("created_at").default("sql`(CURRENT_TIMESTAMP)`").notNull(),
	usedForm: text("used_form"),
},
	(table) => [
		check("chk_tasks_type_enum", sql`"tasks"."type" IN ('article_generation'`),
		check("chk_tasks_trigger_source_enum", sql`"tasks"."trigger_source" IN ('manual', 'cron'`),
		check("chk_tasks_status_enum", sql`"tasks"."status" IN ('queued', 'running', 'succeeded', 'failed', 'canceled'`),
		check("chk_tasks_result_json_valid", sql`"tasks"."result_json" IS NULL OR json_valid("tasks"."result_json"`),
		check("chk_tasks_error_context_json_valid", sql`"tasks"."error_context_json" IS NULL OR json_valid("tasks"."error_context_json"`),
		check("chk_tasks_published_only_for_article_generation", sql`"tasks"."type" = 'article_generation' OR "tasks"."published_at" IS NULL`),
		check("chk_words_origin_enum", sql`"words"."origin" IN ('shanbay', 'article', 'manual'`),
		check("chk_awi_role_enum", sql`"article_word_index"."role" IN ('keyword', 'entity'`),
		check("chk_articles_status_enum", sql`"articles"."status" IN ('draft', 'published'`),
		check("chk_highlights_start_meta_json_valid", sql`json_valid("highlights"."start_meta_json"`),
		check("chk_highlights_end_meta_json_valid", sql`json_valid("highlights"."end_meta_json"`),
		check("chk_highlights_style_json_valid", sql`"highlights"."style_json" IS NULL OR json_valid("highlights"."style_json"`),
		check("chk_daily_word_ref_type_enum", sql`"daily_word_references"."type" IN ('new', 'review'`),
		check("chk_generation_profiles_concurrency_gt0", sql`"generation_profiles"."concurrency" > 0`),
		check("chk_generation_profiles_timeout_ms_gt0", sql`"generation_profiles"."timeout_ms" > 0`),
	]);

export const tasks = sqliteTable("tasks", {
	id: text().primaryKey().notNull(),
	taskDate: text("task_date").notNull(),
	type: text().notNull(),
	triggerSource: text("trigger_source").default("manual").notNull(),
	status: text().notNull(),
	profileId: text("profile_id").notNull().references(() => generationProfiles.id),
	resultJson: text("result_json"),
	errorMessage: text("error_message"),
	errorContextJson: text("error_context_json"),
	version: integer().default(0).notNull(),
	createdAt: text("created_at").default("sql`(CURRENT_TIMESTAMP)`").notNull(),
	startedAt: text("started_at"),
	finishedAt: text("finished_at"),
	publishedAt: text("published_at"),
},
	(table) => [
		check("chk_tasks_type_enum", sql`"tasks"."type" IN ('article_generation'`),
		check("chk_tasks_trigger_source_enum", sql`"tasks"."trigger_source" IN ('manual', 'cron'`),
		check("chk_tasks_status_enum", sql`"tasks"."status" IN ('queued', 'running', 'succeeded', 'failed', 'canceled'`),
		check("chk_tasks_result_json_valid", sql`"tasks"."result_json" IS NULL OR json_valid("tasks"."result_json"`),
		check("chk_tasks_error_context_json_valid", sql`"tasks"."error_context_json" IS NULL OR json_valid("tasks"."error_context_json"`),
		check("chk_tasks_published_only_for_article_generation", sql`"tasks"."type" = 'article_generation' OR "tasks"."published_at" IS NULL`),
		check("chk_words_origin_enum", sql`"words"."origin" IN ('shanbay', 'article', 'manual'`),
		check("chk_awi_role_enum", sql`"article_word_index"."role" IN ('keyword', 'entity'`),
		check("chk_articles_status_enum", sql`"articles"."status" IN ('draft', 'published'`),
		check("chk_highlights_start_meta_json_valid", sql`json_valid("highlights"."start_meta_json"`),
		check("chk_highlights_end_meta_json_valid", sql`json_valid("highlights"."end_meta_json"`),
		check("chk_highlights_style_json_valid", sql`"highlights"."style_json" IS NULL OR json_valid("highlights"."style_json"`),
		check("chk_daily_word_ref_type_enum", sql`"daily_word_references"."type" IN ('new', 'review'`),
		check("chk_generation_profiles_concurrency_gt0", sql`"generation_profiles"."concurrency" > 0`),
		check("chk_generation_profiles_timeout_ms_gt0", sql`"generation_profiles"."timeout_ms" > 0`),
	]);

export const words = sqliteTable("words", {
	word: text().primaryKey().notNull(),
	masteryStatus: text("mastery_status").default("unknown").notNull(),
	origin: text().notNull(),
	originRef: text("origin_ref"),
	createdAt: text("created_at").default("sql`(CURRENT_TIMESTAMP)`").notNull(),
	updatedAt: text("updated_at").default("sql`(CURRENT_TIMESTAMP)`").notNull(),
},
	(table) => [
		check("chk_tasks_type_enum", sql`"tasks"."type" IN ('article_generation'`),
		check("chk_tasks_trigger_source_enum", sql`"tasks"."trigger_source" IN ('manual', 'cron'`),
		check("chk_tasks_status_enum", sql`"tasks"."status" IN ('queued', 'running', 'succeeded', 'failed', 'canceled'`),
		check("chk_tasks_result_json_valid", sql`"tasks"."result_json" IS NULL OR json_valid("tasks"."result_json"`),
		check("chk_tasks_error_context_json_valid", sql`"tasks"."error_context_json" IS NULL OR json_valid("tasks"."error_context_json"`),
		check("chk_tasks_published_only_for_article_generation", sql`"tasks"."type" = 'article_generation' OR "tasks"."published_at" IS NULL`),
		check("chk_words_origin_enum", sql`"words"."origin" IN ('shanbay', 'article', 'manual'`),
		check("chk_awi_role_enum", sql`"article_word_index"."role" IN ('keyword', 'entity'`),
		check("chk_articles_status_enum", sql`"articles"."status" IN ('draft', 'published'`),
		check("chk_highlights_start_meta_json_valid", sql`json_valid("highlights"."start_meta_json"`),
		check("chk_highlights_end_meta_json_valid", sql`json_valid("highlights"."end_meta_json"`),
		check("chk_highlights_style_json_valid", sql`"highlights"."style_json" IS NULL OR json_valid("highlights"."style_json"`),
		check("chk_daily_word_ref_type_enum", sql`"daily_word_references"."type" IN ('new', 'review'`),
		check("chk_generation_profiles_concurrency_gt0", sql`"generation_profiles"."concurrency" > 0`),
		check("chk_generation_profiles_timeout_ms_gt0", sql`"generation_profiles"."timeout_ms" > 0`),
	]);

export const articleWordIndex = sqliteTable("article_word_index", {
	id: text().primaryKey().notNull(),
	word: text().notNull(),
	articleId: text("article_id").notNull().references(() => articles.id, { onDelete: "cascade" }),
	contextSnippet: text("context_snippet").notNull(),
	role: text().notNull(),
	createdAt: text("created_at").default("sql`(CURRENT_TIMESTAMP)`").notNull(),
},
	(table) => [
		check("chk_tasks_type_enum", sql`"tasks"."type" IN ('article_generation'`),
		check("chk_tasks_trigger_source_enum", sql`"tasks"."trigger_source" IN ('manual', 'cron'`),
		check("chk_tasks_status_enum", sql`"tasks"."status" IN ('queued', 'running', 'succeeded', 'failed', 'canceled'`),
		check("chk_tasks_result_json_valid", sql`"tasks"."result_json" IS NULL OR json_valid("tasks"."result_json"`),
		check("chk_tasks_error_context_json_valid", sql`"tasks"."error_context_json" IS NULL OR json_valid("tasks"."error_context_json"`),
		check("chk_tasks_published_only_for_article_generation", sql`"tasks"."type" = 'article_generation' OR "tasks"."published_at" IS NULL`),
		check("chk_words_origin_enum", sql`"words"."origin" IN ('shanbay', 'article', 'manual'`),
		check("chk_awi_role_enum", sql`"article_word_index"."role" IN ('keyword', 'entity'`),
		check("chk_articles_status_enum", sql`"articles"."status" IN ('draft', 'published'`),
		check("chk_highlights_start_meta_json_valid", sql`json_valid("highlights"."start_meta_json"`),
		check("chk_highlights_end_meta_json_valid", sql`json_valid("highlights"."end_meta_json"`),
		check("chk_highlights_style_json_valid", sql`"highlights"."style_json" IS NULL OR json_valid("highlights"."style_json"`),
		check("chk_daily_word_ref_type_enum", sql`"daily_word_references"."type" IN ('new', 'review'`),
		check("chk_generation_profiles_concurrency_gt0", sql`"generation_profiles"."concurrency" > 0`),
		check("chk_generation_profiles_timeout_ms_gt0", sql`"generation_profiles"."timeout_ms" > 0`),
	]);

export const articles = sqliteTable("articles", {
	id: text().primaryKey().notNull(),
	generationTaskId: text("generation_task_id").notNull().references(() => tasks.id, { onDelete: "cascade" }),
	model: text().notNull(),
	variant: integer().notNull(),
	title: text().notNull(),
	sourceUrl: text("source_url"),
	status: text().notNull(),
	readLevels: integer("read_levels").default(0).notNull(),
	createdAt: text("created_at").default("sql`(CURRENT_TIMESTAMP)`").notNull(),
	publishedAt: text("published_at"),
},
	(table) => [
		check("chk_tasks_type_enum", sql`"tasks"."type" IN ('article_generation'`),
		check("chk_tasks_trigger_source_enum", sql`"tasks"."trigger_source" IN ('manual', 'cron'`),
		check("chk_tasks_status_enum", sql`"tasks"."status" IN ('queued', 'running', 'succeeded', 'failed', 'canceled'`),
		check("chk_tasks_result_json_valid", sql`"tasks"."result_json" IS NULL OR json_valid("tasks"."result_json"`),
		check("chk_tasks_error_context_json_valid", sql`"tasks"."error_context_json" IS NULL OR json_valid("tasks"."error_context_json"`),
		check("chk_tasks_published_only_for_article_generation", sql`"tasks"."type" = 'article_generation' OR "tasks"."published_at" IS NULL`),
		check("chk_words_origin_enum", sql`"words"."origin" IN ('shanbay', 'article', 'manual'`),
		check("chk_awi_role_enum", sql`"article_word_index"."role" IN ('keyword', 'entity'`),
		check("chk_articles_status_enum", sql`"articles"."status" IN ('draft', 'published'`),
		check("chk_highlights_start_meta_json_valid", sql`json_valid("highlights"."start_meta_json"`),
		check("chk_highlights_end_meta_json_valid", sql`json_valid("highlights"."end_meta_json"`),
		check("chk_highlights_style_json_valid", sql`"highlights"."style_json" IS NULL OR json_valid("highlights"."style_json"`),
		check("chk_daily_word_ref_type_enum", sql`"daily_word_references"."type" IN ('new', 'review'`),
		check("chk_generation_profiles_concurrency_gt0", sql`"generation_profiles"."concurrency" > 0`),
		check("chk_generation_profiles_timeout_ms_gt0", sql`"generation_profiles"."timeout_ms" > 0`),
	]);

export const highlights = sqliteTable("highlights", {
	id: text().primaryKey().notNull(),
	articleId: text("article_id").notNull().references(() => articles.id, { onDelete: "cascade" }),
	actor: text().notNull(),
	startMetaJson: text("start_meta_json").notNull(),
	endMetaJson: text("end_meta_json").notNull(),
	text: text().notNull(),
	note: text(),
	styleJson: text("style_json"),
	createdAt: text("created_at").default("sql`(CURRENT_TIMESTAMP)`").notNull(),
	updatedAt: text("updated_at").default("sql`(CURRENT_TIMESTAMP)`").notNull(),
	deletedAt: text("deleted_at"),
},
	(table) => [
		check("chk_tasks_type_enum", sql`"tasks"."type" IN ('article_generation'`),
		check("chk_tasks_trigger_source_enum", sql`"tasks"."trigger_source" IN ('manual', 'cron'`),
		check("chk_tasks_status_enum", sql`"tasks"."status" IN ('queued', 'running', 'succeeded', 'failed', 'canceled'`),
		check("chk_tasks_result_json_valid", sql`"tasks"."result_json" IS NULL OR json_valid("tasks"."result_json"`),
		check("chk_tasks_error_context_json_valid", sql`"tasks"."error_context_json" IS NULL OR json_valid("tasks"."error_context_json"`),
		check("chk_tasks_published_only_for_article_generation", sql`"tasks"."type" = 'article_generation' OR "tasks"."published_at" IS NULL`),
		check("chk_words_origin_enum", sql`"words"."origin" IN ('shanbay', 'article', 'manual'`),
		check("chk_awi_role_enum", sql`"article_word_index"."role" IN ('keyword', 'entity'`),
		check("chk_articles_status_enum", sql`"articles"."status" IN ('draft', 'published'`),
		check("chk_highlights_start_meta_json_valid", sql`json_valid("highlights"."start_meta_json"`),
		check("chk_highlights_end_meta_json_valid", sql`json_valid("highlights"."end_meta_json"`),
		check("chk_highlights_style_json_valid", sql`"highlights"."style_json" IS NULL OR json_valid("highlights"."style_json"`),
		check("chk_daily_word_ref_type_enum", sql`"daily_word_references"."type" IN ('new', 'review'`),
		check("chk_generation_profiles_concurrency_gt0", sql`"generation_profiles"."concurrency" > 0`),
		check("chk_generation_profiles_timeout_ms_gt0", sql`"generation_profiles"."timeout_ms" > 0`),
	]);

export const dailyWordReferences = sqliteTable("daily_word_references", {
	id: text().primaryKey().notNull(),
	date: text().notNull(),
	word: text().notNull().references(() => words.word, { onDelete: "cascade" }),
	type: text().notNull(),
	createdAt: text("created_at").default("sql`(CURRENT_TIMESTAMP)`").notNull(),
},
	(table) => [
		check("chk_tasks_type_enum", sql`"tasks"."type" IN ('article_generation'`),
		check("chk_tasks_trigger_source_enum", sql`"tasks"."trigger_source" IN ('manual', 'cron'`),
		check("chk_tasks_status_enum", sql`"tasks"."status" IN ('queued', 'running', 'succeeded', 'failed', 'canceled'`),
		check("chk_tasks_result_json_valid", sql`"tasks"."result_json" IS NULL OR json_valid("tasks"."result_json"`),
		check("chk_tasks_error_context_json_valid", sql`"tasks"."error_context_json" IS NULL OR json_valid("tasks"."error_context_json"`),
		check("chk_tasks_published_only_for_article_generation", sql`"tasks"."type" = 'article_generation' OR "tasks"."published_at" IS NULL`),
		check("chk_words_origin_enum", sql`"words"."origin" IN ('shanbay', 'article', 'manual'`),
		check("chk_awi_role_enum", sql`"article_word_index"."role" IN ('keyword', 'entity'`),
		check("chk_articles_status_enum", sql`"articles"."status" IN ('draft', 'published'`),
		check("chk_highlights_start_meta_json_valid", sql`json_valid("highlights"."start_meta_json"`),
		check("chk_highlights_end_meta_json_valid", sql`json_valid("highlights"."end_meta_json"`),
		check("chk_highlights_style_json_valid", sql`"highlights"."style_json" IS NULL OR json_valid("highlights"."style_json"`),
		check("chk_daily_word_ref_type_enum", sql`"daily_word_references"."type" IN ('new', 'review'`),
		check("chk_generation_profiles_concurrency_gt0", sql`"generation_profiles"."concurrency" > 0`),
		check("chk_generation_profiles_timeout_ms_gt0", sql`"generation_profiles"."timeout_ms" > 0`),
	]);

export const generationProfiles = sqliteTable("generation_profiles", {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	topicPreference: text("topic_preference").notNull(),
	concurrency: integer().notNull(),
	timeoutMs: integer("timeout_ms").notNull(),
	createdAt: text("created_at").default("sql`(CURRENT_TIMESTAMP)`").notNull(),
	updatedAt: text("updated_at").default("sql`(CURRENT_TIMESTAMP)`").notNull(),
},
	(table) => [
		check("chk_tasks_type_enum", sql`"tasks"."type" IN ('article_generation'`),
		check("chk_tasks_trigger_source_enum", sql`"tasks"."trigger_source" IN ('manual', 'cron'`),
		check("chk_tasks_status_enum", sql`"tasks"."status" IN ('queued', 'running', 'succeeded', 'failed', 'canceled'`),
		check("chk_tasks_result_json_valid", sql`"tasks"."result_json" IS NULL OR json_valid("tasks"."result_json"`),
		check("chk_tasks_error_context_json_valid", sql`"tasks"."error_context_json" IS NULL OR json_valid("tasks"."error_context_json"`),
		check("chk_tasks_published_only_for_article_generation", sql`"tasks"."type" = 'article_generation' OR "tasks"."published_at" IS NULL`),
		check("chk_words_origin_enum", sql`"words"."origin" IN ('shanbay', 'article', 'manual'`),
		check("chk_awi_role_enum", sql`"article_word_index"."role" IN ('keyword', 'entity'`),
		check("chk_articles_status_enum", sql`"articles"."status" IN ('draft', 'published'`),
		check("chk_highlights_start_meta_json_valid", sql`json_valid("highlights"."start_meta_json"`),
		check("chk_highlights_end_meta_json_valid", sql`json_valid("highlights"."end_meta_json"`),
		check("chk_highlights_style_json_valid", sql`"highlights"."style_json" IS NULL OR json_valid("highlights"."style_json"`),
		check("chk_daily_word_ref_type_enum", sql`"daily_word_references"."type" IN ('new', 'review'`),
		check("chk_generation_profiles_concurrency_gt0", sql`"generation_profiles"."concurrency" > 0`),
		check("chk_generation_profiles_timeout_ms_gt0", sql`"generation_profiles"."timeout_ms" > 0`),
	]);

export const articleVariants = sqliteTable("article_variants", {
	id: text().primaryKey().notNull(),
	articleId: text("article_id").notNull().references(() => articles.id, { onDelete: "cascade" }),
	level: integer().notNull(),
	levelLabel: text("level_label").notNull(),
	title: text().notNull(),
	content: text().notNull(),
	syntaxJson: text("syntax_json"),
	sentencesJson: text("sentences_json"),
	createdAt: text("created_at").default("sql`(CURRENT_TIMESTAMP)`").notNull(),
},
	(table) => [
		index("idx_article_variant_article_id").on(table.articleId),
		uniqueIndex("uq_article_variant_level").on(table.articleId, table.level),
		check("chk_tasks_type_enum", sql`"tasks"."type" IN ('article_generation'`),
		check("chk_tasks_trigger_source_enum", sql`"tasks"."trigger_source" IN ('manual', 'cron'`),
		check("chk_tasks_status_enum", sql`"tasks"."status" IN ('queued', 'running', 'succeeded', 'failed', 'canceled'`),
		check("chk_tasks_result_json_valid", sql`"tasks"."result_json" IS NULL OR json_valid("tasks"."result_json"`),
		check("chk_tasks_error_context_json_valid", sql`"tasks"."error_context_json" IS NULL OR json_valid("tasks"."error_context_json"`),
		check("chk_tasks_published_only_for_article_generation", sql`"tasks"."type" = 'article_generation' OR "tasks"."published_at" IS NULL`),
		check("chk_words_origin_enum", sql`"words"."origin" IN ('shanbay', 'article', 'manual'`),
		check("chk_awi_role_enum", sql`"article_word_index"."role" IN ('keyword', 'entity'`),
		check("chk_articles_status_enum", sql`"articles"."status" IN ('draft', 'published'`),
		check("chk_highlights_start_meta_json_valid", sql`json_valid("highlights"."start_meta_json"`),
		check("chk_highlights_end_meta_json_valid", sql`json_valid("highlights"."end_meta_json"`),
		check("chk_highlights_style_json_valid", sql`"highlights"."style_json" IS NULL OR json_valid("highlights"."style_json"`),
		check("chk_daily_word_ref_type_enum", sql`"daily_word_references"."type" IN ('new', 'review'`),
		check("chk_generation_profiles_concurrency_gt0", sql`"generation_profiles"."concurrency" > 0`),
		check("chk_generation_profiles_timeout_ms_gt0", sql`"generation_profiles"."timeout_ms" > 0`),
	]);

